### ISSUE TITLE
Final standings page doesn't show

### ISSUE THREAD

**Issue by siddhp1** [hlsschessclub/Scheveningen#7]
The final standings page doesn't come up. I am not sure if this is because the round numbers are hard-coded and it comes up after 8 rounds, but if there are less than 8 players per team it breaks after the round number exceeds the number of players on a team. 

Also, the standings tables (current and final) have 8 round columns hard-coded in HTML, but the number of columns should correspond to the number of players on a team.

**Comment by BrianZhang1** [comment]
apologies for that, I mistakenly thought that 8 rounds was hard coded. Just created a pull request for a fix, give it a look.
